name: Deploy DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy DAGs to Airflow server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}  # Используем пароль
          port: 22
          source: "dags/*"
          target: "/home/airflow_user/airflow/dags/"
